[build]
  command = "npm run build"
  publish = "_site"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/private/guida_7_step.pdf"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline' https://js.stripe.com; connect-src 'self' https://api.stripe.com; frame-src https://js.stripe.com; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "/grazie"
  to   = "/grazie/"
  status = 301